### ISSUE TITLE
How can I add dynamic items(values) for menuItems?

### ISSUE THREAD

**Issue by RiyaNainwani** [AlenToma/react-native-selectable-text#10]
Not able to find any reference for the menuItems how can I add the dynamic values for menuItems in the items of an array according to the applied conditions that if selectable text is already highlighted, then display "delete-highlight" in menuItems and if selectableText has no highlight then display "Highlight" in menuItems.

If anybody has an idea to solve this kind of issue?

**Comment by rahulbmoon** [comment]
any updates on this issue ?

**Comment by RiyaNainwani** [comment]
No Sir

**Comment by AlenToma** [comment]
Jsut assign `menuItems` to a usestate variable should do the trick.

**Comment by RiyaNainwani** [comment]
Hello @AlenToma, as above mentioned issue is based on the text we are getting with it's initial and final point of selectable text but the condition is that we want the `menuItems` dynamically based on the text is already selectable or not, getting text (with it's starting and end points) before `onPress` event of button so we can check that text is already selected or highlighted or not. If text is not already selected then `menuItems` should show the two different values like `highlight` & `note` else should show `note` & `delete-highlight`.

Any Idea if You have to solve this issue will be appreciated, please share.Thank you for replying.

**Comment by AlenToma** [comment]
There is onHighlightPress prob. There you may be able to customize the components to your requirement.
