### ISSUE TITLE
How to use this module in react native expo?

### ISSUE THREAD

**Issue by ParkSeungwon** [AlenToma/react-native-selectable-text#13]
I got this error in react native expo-web.

/node_modules/@alentoma/react-native-selectable-text/demo/SelectableText.tsx 8:7 
Module parse failed: Unexpected token (8:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| const RNSelectableText = requireNativeComponent('RNSelectableText')
> export interface IHighlights {
|   start: number,
|   end: number,

**Comment by AlenToma** [comment]
Follow the incstruction of [readme ](https://github.com/AlenToma/react-native-selectable-text) as this library dose not have autolink
