### ISSUE TITLE
Xcode build error: 'duplicate symbols for architecture x86_64'

### ISSUE THREAD

**Issue by Bruce773** [AlenToma/react-native-selectable-text#5]
I'm getting a build error from Xcode: `duplicate symbols for architecture x86_64`

I'm using `Alternative 2` to link the Pod stuff... ie. adding `pod 'RNSelectableText', :path => '../node_modules/@alentoma/react-native-selectable-text/ios/RNSelectableText.podspec'` to `ios/Podfile`.

So, my `ios/Podfile` looks like this at the top:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

pod 'RNSelectableText', :path => '../node_modules/@alentoma/react-native-selectable-text/ios/RNSelectableText.podspec'

target 'BibleMarkup2' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
...
```

### ERROR SCREENSHOT:
![Screen Shot 2022-06-08 at 10 06 56](https://user-images.githubusercontent.com/29665383/172673890-f900e75f-93f6-4e2c-8f38-bcb3571ca80d.png)

### THINGS I'VE TRIED 👨‍💻 

- (1) Deleting `node_modules`, (2) running `yarn`, (3) deleting `ios/Pods` and `Podfile.lock`, (4) running `npx pod-install`

- (1) Deleting `main.m` and `AppDelegate.mm` from `Project > Targets > Build Phases > Compile Sources` (2) cleaning build folder (3) running build (4) re-adding those two files   <- This whole process was to help _force_ a full-blown recompile, so I've heard... 🤔 

- `Alternative 1` is hit or miss for me, in terms of building... but, when it does build, I get an error complaining that the text I pass to `SelectableText` via the `value` prop is not in a `Text` component:

![Screen Shot 2022-06-08 at 11 09 18](https://user-images.githubusercontent.com/29665383/172676488-9400657f-de90-4f1b-8e10-532a15dfd3b5.png)

**Comment by Bruce773** [comment]
Ended up solving by deleting `pod 'RNSelectableText', :path => '../node_modules/@alentoma/react-native-selectable-text/ios/RNSelectableText.podspec'` from `ios/Podfile` and running `react-native link @alentoma/react-native-selectable-text`, instead. 🎉 🙂

**Comment by araujobarret** [comment]
I still have the same error, manually linking with react-native link didn't work for me :/
tried with RN 0.66 and 0.68, same error
